services:
  farmerbot:
    image: ghcr.io/threefoldtech/farmerbot:0.1.0-rc2
    depends_on:
      redis:
        condition: service_healthy
      rmbpeer:
        condition: service_started
      grid3_client:
        condition: service_started
    volumes:
      - /work/farmerbot/_brandon_farm:/farmerbot
    network_mode: host
    command: -c /farmerbot/ --output /farmerbot/farmerbot.log --debug

  rmbpeer:
    image: ghcr.io/threefoldtech/rmb-peer:latest
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - '80'
      - '8080'
      - '443'
    ports:
      - '80'
      - '8080'
      - '443'
    network_mode: host
    volumes:
      - /work/farmerbot/_rmb_peer:/rmbpeer
    entrypoint: /usr/sbin/rmb-peer -m "fade among level alarm stereo upset saddle fury fragile supreme cricket chicken" --relay wss://relay.dev.grid.tf:443 -s wss://tfchain.dev.grid.tf:443 -dd
    

  grid3_client:
    image: grid3_client:latest
    volumes:
      - /work/farmerbot/_grid3_client:/grid3_client
    depends_on:
      redis:
        condition: service_healthy
    command: httpserver -c /grid3_client/http-server-config.json
    ports:
      - '3000'
    network_mode: host

  redis:
    image: redis:7.0.8-alpine
    restart: always
    ports:
      - '6379'
    expose:
      - '6379'
    command: --save 20 1
    volumes: 
      - db:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    network_mode: host

volumes:
  db:
    driver: local
