services:
  farmerbot:
    image: test:latest #ghcr.io/threefoldtech/farmerbot:0.1.0-rc3
    depends_on:
      redis:
        condition: service_healthy
      rmbpeer:
        condition: service_started
      grid3_client:
        condition: service_healthy
    volumes:
      - /work/farmerbot/_brandon_farm:/farmerbot
    command: -c /farmerbot/ --grid3 "http://grid3_client:3000" --redis "redis:6379" --debug #--output /farmerbot/farmerbot.log

  rmbpeer:
    image: ghcr.io/threefoldtech/rmb-peer:latest
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - /work/farmerbot/_rmb_peer:/rmbpeer
    entrypoint: /bin/sh -c
    #network_mode: host
    command: ["/usr/sbin/rmb-peer --redis redis://redis:6379 --mnemonics \"$(cat /rmbpeer/mnemonic.txt)\" --relay wss://relay.dev.grid.tf:443 -s wss://tfchain.dev.grid.tf:443 -d"]

  grid3_client:
    image: ghcr.io/threefoldtech/grid3_client_ts:2.0.0-rc4
    volumes:
      - /work/farmerbot/_grid3_client:/grid3_client
    depends_on:
      redis:
        condition: service_healthy
    command: httpserver -c /grid3_client/http-server-config.json
    ports:
      - '3000'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -X POST -H \"Content-Type: application/json\" http://127.0.0.1:3000/twins/get_my_twin_id || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7.0.8-alpine
    restart: always
    ports:
      - '6379'
    expose:
      - '6379'
    command: --save 20 1
    volumes: 
      - db:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  db:
    driver: local
