name: Build and Test
on: 
  push:
    branches:
      - development
  pull_request:
jobs:
  build-and-test:
    runs-on: [self-hosted, tfchainrunner01]
    container:
      image: thevlang/vlang:latest

    steps:
      - uses: actions/checkout@v3

      - name: Istall dependencies
        run: |
          cd ../ && git clone -b development_actor https://github.com/freeflowuniverse/baobab.git
          cd baobab && bash install.sh
          cd ../ && git clone -b development_38 https://github.com/freeflowuniverse/crystallib.git
          cd crystallib && bash install.sh
          cd ../

      - name: Build
        run: |
          bash install.sh
          v main.v

      - name: Unit tests
        run: |
          bash tests/run_tests.sh