name: Build and Test

on: 
  push:
    #branches:
    #  - development
  pull_request:
  workflow_dispatch:
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --net host
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install dependencies
        run: sudo apt install -y libgc-dev tmux mc git rsync curl

      - name: Setup Vlang
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      
      # - name: Start Redis
      #   uses: supercharge/redis-github-action@1.5.0
      #   with:
      #     redis-version: 7.0.8

      - uses: actions/checkout@v3

      # TODO release the dependencies mentioned below!
      - name: Istall dependencies
        run: |
          cd ../ && git clone -b development_actor https://github.com/freeflowuniverse/baobab.git
          cd baobab && bash install.sh
          cd ../ && git clone -b development https://github.com/freeflowuniverse/crystallib.git
          cd crystallib && bash install.sh
          cd ../

      - name: Build
        run: |
          bash install.sh
          v main.v

      - name: Unit tests
        run: |
          bash tests/run_tests.sh