name: Build and Test

on: 
  push:
    #branches:
    #  - development
  pull_request:
  workflow_dispatch:
  
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: threefolddev/farmerbot:0

    steps:
      - uses: actions/checkout@v3

      - name: Setup Vlang
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      # TODO release the dependencies mentioned below!
      - name: Istall dependencies
        run: |
          cd ../ && git clone -b development_actor https://github.com/freeflowuniverse/baobab.git
          cd baobab && bash install.sh
          cd ../ && git clone -b development_38 https://github.com/freeflowuniverse/crystallib.git
          cd crystallib && bash install.sh
          cd ../
          /etc/init.d/redis-server start

      - name: Build
        run: |
          bash install.sh
          v main.v

      - name: Unit tests
        run: |
          bash tests/run_tests.sh