name: Publish ARM

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - dockerfile: ./arm/Dockerfile
            image: ghcr.io/${{ github.repository }}
          - dockerfile: ./arm/file_creator/Dockerfile
            image: ghcr.io/${{ github.repository }}_config
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          flavor: |
            suffix=-arm,onlatest=true
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: linux/arm64,linux/armhf
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
